// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Go HTTP client library for the inventory API.
// Generated from: pkg/codegen/templates/client.go.tmpl
//
// To modify the client:
//   1. Edit the template file: pkg/codegen/templates/client.go.tmpl
//   2. Run 'fabrica generate' to regenerate
//   3. Do NOT edit this file directly - changes will be lost
//
// Generated client methods for each resource:
//   - GetResources(ctx) - List all resources
//   - GetResource(ctx, uid) - Get specific resource by UID
//   - CreateResource(ctx, req) - Create new resource
//   - UpdateResource(ctx, uid, req) - Update existing resource spec
//   - PatchResource(ctx, uid, patchData, contentType) - Patch existing resource spec
//   - UpdateResourceStatus(ctx, uid, status) - Update resource status only
//   - PatchResourceStatus(ctx, uid, patchData) - Patch resource status only
//   - DeleteResource(ctx, uid) - Delete resource
//
// Usage example:
//   client, err := client.NewClient("http://localhost:8080", nil)
//   if err != nil {
//       log.Fatal(err)
//   }
//
//   bmcs, err := client.GetBMCs(context.Background())
//   if err != nil {
//       log.Fatal(err)
//   }
//
// To add authentication:
//   1. Create custom http.Client with auth transport
//   2. Pass it to NewClient:
//      httpClient := &http.Client{
//          Transport: &AuthTransport{Token: "your-token"},
//      }
//      client, _ := client.NewClient(baseURL, httpClient)
//
// To add custom headers:
//   1. Modify doRequest method to accept header options
//   2. Or wrap http.Client with custom RoundTripper
//
// To handle retries:
//   1. Wrap http.Client with retry transport
//   2. Use github.com/hashicorp/go-retryablehttp or similar
//

package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"

	"github.com/example/bmc-manager/apis/example.fabrica.dev/v1"
)

// Client provides access to the inventory API
type Client struct {
	baseURL     *url.URL
	httpClient  *http.Client
	version     string // Optional API version for Accept/Content-Type headers
	bearerToken string // Optional JWT bearer token for Authorization header
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// NewClient creates a new API client
func NewClient(baseURL string, httpClient *http.Client) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	return &Client{
		baseURL:    u,
		httpClient: httpClient,
	}, nil
}

// NewClientWithBearerToken creates a new API client configured with a JWT bearer token.
func NewClientWithBearerToken(baseURL, bearerToken string, httpClient *http.Client) (*Client, error) {
	c, err := NewClient(baseURL, httpClient)
	if err != nil {
		return nil, err
	}
	return c.WithBearerToken(bearerToken), nil
}

// WithVersion returns a new client configured to use a specific API version
func (c *Client) WithVersion(version string) *Client {
	return &Client{
		baseURL:     c.baseURL,
		httpClient:  c.httpClient,
		version:     version,
		bearerToken: c.bearerToken,
	}
}

// WithBearerToken returns a new client configured to send Authorization: Bearer <token>.
func (c *Client) WithBearerToken(token string) *Client {
	return &Client{
		baseURL:     c.baseURL,
		httpClient:  c.httpClient,
		version:     c.version,
		bearerToken: token,
	}
}

// doRequest performs an HTTP request and handles the response
func (c *Client) doRequest(ctx context.Context, method, endpoint string, body interface{}, result interface{}) error {
	var reqBody io.Reader
	if body != nil {
		jsonData, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewBuffer(jsonData)
	}

	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, method, u.String(), reqBody)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set Content-Type and Accept headers with optional version
	contentType := "application/json"
	acceptType := "application/json"
	if c.version != "" {
		contentType = fmt.Sprintf("application/json;version=%s", c.version)
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}

	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	req.Header.Set("Accept", acceptType)
	if c.bearerToken != "" {
		req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", c.bearerToken))
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// doPatchRequest performs a PATCH request with custom content type
func (c *Client) doPatchRequest(ctx context.Context, endpoint string, patchData []byte, contentType string, result interface{}) error {
	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, "PATCH", u.String(), bytes.NewBuffer(patchData))
	if err != nil {
		return fmt.Errorf("failed to create patch request: %w", err)
	}

	// Set patch-specific Content-Type
	req.Header.Set("Content-Type", contentType)

	// Set Accept header with optional version
	acceptType := "application/json"
	if c.version != "" {
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}
	req.Header.Set("Accept", acceptType)
	if c.bearerToken != "" {
		req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", c.bearerToken))
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("patch request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read patch response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("PATCH HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("PATCH API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal patch response: %w", err)
		}
	}

	return nil
}

// GetBMCCredentials retrieves all bmccredentials
func (c *Client) GetBMCCredentials(ctx context.Context) ([]v1.BMCCredential, error) {
	var response []v1.BMCCredential
	if err := c.doRequest(ctx, "GET", "/bmccredentials", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetBMCCredential retrieves a specific BMCCredential by UID
func (c *Client) GetBMCCredential(ctx context.Context, uid string) (*v1.BMCCredential, error) {
	var result v1.BMCCredential
	endpoint := fmt.Sprintf("/bmccredentials/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateBMCCredential creates a new BMCCredential
func (c *Client) CreateBMCCredential(ctx context.Context, req CreateBMCCredentialRequest) (*v1.BMCCredential, error) {
	var result v1.BMCCredential
	if err := c.doRequest(ctx, "POST", "/bmccredentials", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateBMCCredential updates an existing BMCCredential
func (c *Client) UpdateBMCCredential(ctx context.Context, uid string, req UpdateBMCCredentialRequest) (*v1.BMCCredential, error) {
	var result v1.BMCCredential
	endpoint := fmt.Sprintf("/bmccredentials/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchBMCCredential patches an existing BMCCredential spec with the specified patch data and content type
func (c *Client) PatchBMCCredential(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.BMCCredential, error) {
	var result v1.BMCCredential
	endpoint := fmt.Sprintf("/bmccredentials/%s", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateBMCCredentialStatus updates only the status of an existing BMCCredential
// This method is intended for controllers, reconcilers, and monitoring systems.
// It preserves the spec and only updates the status portion of the resource.
func (c *Client) UpdateBMCCredentialStatus(ctx context.Context, uid string, status v1.BMCCredentialStatus) (*v1.BMCCredential, error) {
	var result v1.BMCCredential
	endpoint := fmt.Sprintf("/bmccredentials/%s/status", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, status, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// PatchBMCCredentialStatus patches only the status of an existing BMCCredential
// Supports JSON Merge Patch by default. Use PatchBMCCredentialStatusWithType for other patch formats.
func (c *Client) PatchBMCCredentialStatus(ctx context.Context, uid string, patchData []byte) (*v1.BMCCredential, error) {
	return c.PatchBMCCredentialStatusWithType(ctx, uid, patchData, "application/merge-patch+json")
}

// PatchBMCCredentialStatusWithType patches status with a specific patch content type
// Supported types: application/merge-patch+json, application/json-patch+json, application/fabrica-patch+json
func (c *Client) PatchBMCCredentialStatusWithType(ctx context.Context, uid string, patchData []byte, contentType string) (*v1.BMCCredential, error) {
	var result v1.BMCCredential
	endpoint := fmt.Sprintf("/bmccredentials/%s/status", uid)
	if err := c.doPatchRequest(ctx, endpoint, patchData, contentType, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteBMCCredential deletes a BMCCredential by UID
func (c *Client) DeleteBMCCredential(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/bmccredentials/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}
