// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-04-28T16:29:24Z
//
// # Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for BMCCredential resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /bmccredentials (list all bmccredentials)
//   - GET /bmccredentials/{uid} (get specific BMCCredential)
//   - POST /bmccredentials (create new BMCCredential)
//   - PUT /bmccredentials/{uid} (update BMCCredential spec)
//   - PATCH /bmccredentials/{uid} (patch BMCCredential spec)
//   - DELETE /bmccredentials/{uid} (delete BMCCredential)
//   - PUT /bmccredentials/{uid}/status (update BMCCredential status)
//   - PATCH /bmccredentials/{uid}/status (patch BMCCredential status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadBMCCredential*/SaveBMCCredential*/DeleteBMCCredential*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadBMCCredentialWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/example/bmc-manager/apis/example.fabrica.dev/v1"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"

	"github.com/example/bmc-manager/internal/storage"
)

// GetBMCCredentials returns all BMCCredential resources
func GetBMCCredentials(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	bmccredentials, err := storage.LoadAllBMCCredentials(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load bmccredentials: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, bmccredentials)
}

// GetBMCCredential returns a specific BMCCredential resource by UID
func GetBMCCredential(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMCCredential UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadBMCCredential() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	bMCCredential, err := storage.LoadBMCCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMCCredential not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, bMCCredential)
}

// CreateBMCCredential creates a new BMCCredential resource
func CreateBMCCredential(w http.ResponseWriter, r *http.Request) {
	var req CreateBMCCredentialRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("BMCCredential")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	bMCCredential := &v1.BMCCredential{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "BMCCredential",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	bMCCredential.Metadata = req.Metadata
	bMCCredential.Metadata.UID = uid
	now := time.Now()
	bMCCredential.Metadata.CreatedAt = now
	bMCCredential.Metadata.UpdatedAt = now

	// Set labels and annotations
	if bMCCredential.Metadata.Labels == nil {
		bMCCredential.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		bMCCredential.Metadata.Labels[k] = v
	}
	if bMCCredential.Metadata.Annotations == nil {
		bMCCredential.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		bMCCredential.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), bMCCredential); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveBMCCredential(r.Context(), bMCCredential); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BMCCredential: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "BMCCredential", bMCCredential.Metadata.UID, bMCCredential.Metadata.Name, bMCCredential); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for BMCCredential %s: %v\n", bMCCredential.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, bMCCredential)
}

// UpdateBMCCredential updates the spec of an existing BMCCredential resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //bmccredentials/{uid}/status to update status.
func UpdateBMCCredential(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMCCredential UID is required"))
		return
	}

	bMCCredential, err := storage.LoadBMCCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMCCredential not found: %w", err))
		return
	}

	var req UpdateBMCCredentialRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		bMCCredential.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	bMCCredential.Spec = req.AsSpec()

	// Update labels and annotations
	if bMCCredential.Metadata.Labels == nil {
		bMCCredential.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		bMCCredential.Metadata.Labels[k] = v
	}
	if bMCCredential.Metadata.Annotations == nil {
		bMCCredential.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		bMCCredential.Metadata.Annotations[k] = v
	}

	// Update timestamp
	bMCCredential.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveBMCCredential(r.Context(), bMCCredential); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BMCCredential: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": bMCCredential.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "BMCCredential", bMCCredential.Metadata.UID, bMCCredential.Metadata.Name, bMCCredential, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for BMCCredential %s: %v\n", bMCCredential.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, bMCCredential)
}

// PatchBMCCredential patches an existing BMCCredential resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchBMCCredential(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMCCredential UID is required"))
		return
	}

	bMCCredential, err := storage.LoadBMCCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMCCredential not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(bMCCredential.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &bMCCredential.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	bMCCredential.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveBMCCredential(r.Context(), bMCCredential); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched BMCCredential: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": bMCCredential.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "BMCCredential", bMCCredential.Metadata.UID, bMCCredential.Metadata.Name, bMCCredential, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for BMCCredential %s: %v\n", bMCCredential.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, bMCCredential)
}

// UpdateBMCCredentialStatus updates only the status of a BMCCredential resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateBMCCredentialStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMCCredential UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadBMCCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMCCredential not found: %w", err))
		return
	}

	var statusUpdate v1.BMCCredentialStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveBMCCredential(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save BMCCredential status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "BMCCredential", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for BMCCredential %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchBMCCredentialStatus patches only the status of a BMCCredential resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchBMCCredentialStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMCCredential UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadBMCCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMCCredential not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveBMCCredential(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched BMCCredential status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "BMCCredential", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for BMCCredential %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteBMCCredential deletes a BMCCredential resource
func DeleteBMCCredential(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("BMCCredential UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	bMCCredential, err := storage.LoadBMCCredential(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("BMCCredential not found: %w", err))
		return
	}

	if err := storage.DeleteBMCCredential(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete BMCCredential: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "BMCCredential", bMCCredential.Metadata.UID, bMCCredential.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for BMCCredential %s: %v\n", bMCCredential.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "BMCCredential deleted successfully",
		UID:     uid,
	})
}
